#!/bin/bash
#PBS -N gmx_em.pf               # Job name
#PBS -o gmx_em.out              # Output file
#PBS -q normal                  # Queue name
#PBS -l nodes=1:ppn=28          # Number of nodes and processors per node
#PBS -l walltime=48:00:00       # Walltime

# Change to the directory where the job was submitted from
cd /home/tur54445/work/git/peptoid_24summer/test-output/19AE1-4-A/GAFF/protonated/19AE1-4-A_protonated.amb2gmx

# Set the number of OpenMP threads to use
export OMP_NUM_THREADS=1

# Load the necessary modules
module load gromacs/2021.2
module load mpi/openmpi

# Run the GROMACS energy minimization
mpirun mdrun_mpi -s em.tpr -deffnm em

